# Spot Match:

server:
  port: 8002

crypto:
  setting:
    load-symbols-from: db
  match:
    # which ip is slave:
    slaveIp: 10.0.0.0
    snapshot:
      # 快照保存目录:
      dir: /data/spot-match-snapshot
      # 最多保存最近的N个快照:
      max: 20
      # 快照间隔时间，缺省为600秒:
      interval: 600

spring:
  # master-slave data source config: same as api but smaller pool size:
  ex-rw-datasource:
    url: jdbc:mysql://${DB_EX_RW_HOST:${DB_RW_HOST:localhost}}/ex?useSSL=false&characterEncoding=utf8
    username: ex_rw
    password: ${DB_EX_RW_PASSWORD:ex_rw_password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 3000
      max-lifetime: 600000
      maximum-pool-size: 10
      minimum-idle: 2
  # slave datasource:
  ex-ro-datasource:
    url: jdbc:mysql://${DB_EX_RO_HOST:${DB_RO_HOST:localhost}}/ex?useSSL=false&characterEncoding=utf8
    username: ex_ro
    password: ${DB_EX_RO_PASSWORD:ex_ro_password}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: HikariCP
      auto-commit: false
      connection-timeout: 5000
      validation-timeout: 3000
      max-lifetime: 600000
      maximum-pool-size: 10
      minimum-idle: 2
